export const mockProjects = [
  {
    id: 1,
    name: "NAGGW-NGR-KANO-Dambatta-FAGWALAWA",
    description: "Woodlot project in Kano, Nigeria",
    type: 1,
    investment_type: "Carbon Credits",
    area: 5,
    age: 5.25,
    plant_planned: 2000,
    donation: 0,
    coordinates: "12.3084° N, 8.65676° E",
    address: "Dambatta, Kano",
    city: "KANO",
    country: "Nigeria",
    pin_code: "",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e",
    revenue_dist_date: "2025-01-01",
    revenue_dist_details: "Based on carbon credit sales",
    roi: "15%",
    phase: 1,
    donation_method: 1,
    currency: "USD($)",
    funding: {
      total: 100000,
      raised: 75000
    },
    species: {
      species: [{plant: "NEEM", percentage: 100}]
    },
    org_name: "NAGGW",
    org_description: "National Agency for the Great Green Wall",
    org_website: "",
    org_address: "Dambatta, Kano",
    org_country: "Nigeria",
    org_pin_code: "",
    org_reg_id: "",
    carbonCredit_enabled: true,
    estimated_carbon_credits: "251 tCO₂e",
    estimated_survival_rate: "91%",
    project_type: "Woodlot",
    planting_date: "01/2020"
  },
  {
    id: 2,
    name: "NAGGW-NGR-JIGAWA-Sule Tankarkar-JEKE",
    description: "Shelter Belt project in Jigawa, Nigeria",
    type: 2,
    investment_type: "Carbon Credits",
    area: 4.5,
    age: 10.25,
    plant_planned: 2813,
    donation: 0,
    coordinates: "12.78407° N, 9.09152° E",
    address: "Sule Tankarkar, Jigawa",
    city: "JIGAWA",
    country: "Nigeria",
    pin_code: "",
    image: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8",
    revenue_dist_date: "2025-01-01",
    revenue_dist_details: "Based on carbon credit sales",
    roi: "15%",
    phase: 1,
    donation_method: 1,
    currency: "USD($)",
    funding: {
      total: 100000,
      raised: 75000
    },
    species: {
      species: [{plant: "NEEM", percentage: 100}]
    },
    org_name: "NAGGW",
    org_description: "National Agency for the Great Green Wall",
    org_website: "",
    org_address: "Sule Tankarkar, Jigawa",
    org_country: "Nigeria",
    org_pin_code: "",
    org_reg_id: "",
    carbonCredit_enabled: true,
    estimated_carbon_credits: "515 tCO₂e",
    estimated_survival_rate: "89%",
    project_type: "Shelter Belt",
    planting_date: "01/2015"
  },
  {
    id: 3,
    name: "NAGGW-NGR-ADAMAWA-Michika",
    description: "Woodlot project in Adamawa, Nigeria",
    type: 1,
    investment_type: "Carbon Credits",
    area: 30,
    age: 10.25,
    plant_planned: 25031,
    donation: 0,
    coordinates: "10.53894° N, 13.28318° E",
    address: "Michika, Adamawa",
    city: "ADAMAWA",
    country: "Nigeria",
    pin_code: "",
    image: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368",
    revenue_dist_date: "2025-01-01",
    revenue_dist_details: "Based on carbon credit sales",
    roi: "15%",
    phase: 1,
    donation_method: 1,
    currency: "USD($)",
    funding: {
      total: 100000,
      raised: 75000
    },
    species: {
      species: [
        {plant: "EUCALYPTUS", percentage: 50},
        {plant: "NEEM", percentage: 50}
      ]
    },
    org_name: "NAGGW",
    org_description: "National Agency for the Great Green Wall",
    org_website: "",
    org_address: "Michika, Adamawa",
    org_country: "Nigeria",
    org_pin_code: "",
    org_reg_id: "",
    carbonCredit_enabled: true,
    estimated_carbon_credits: "5,230 tCO₂e",
    estimated_survival_rate: "95%",
    project_type: "Woodlot",
    planting_date: "01/2015"
  }
];
